"""Type stubs for py_lean_multisig.

Hand-written, kept in lockstep with the Rust extension. tests/test_stubs.py
runs mypy --strict against an example exercising every export.
"""

from typing import final

__version__: str

@final
class PublicKey:
    @classmethod
    def from_bytes(cls, data: bytes) -> "PublicKey": ...
    def to_bytes(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class SecretKey:
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def slot_start(self) -> int: ...
    @property
    def slot_end(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Signature:
    @classmethod
    def from_bytes(cls, data: bytes) -> "Signature": ...
    def to_bytes(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class AggregatedSignature:
    @classmethod
    def from_bytes(cls, data: bytes) -> "AggregatedSignature": ...
    def to_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

@final
class Prover:
    def __init__(self, *, log_inv_rate: int = ...) -> None: ...
    def aggregate(
        self,
        pub_keys: list[PublicKey],
        signatures: list[Signature],
        message: bytes,
        slot: int,
        *,
        children: list[tuple[list[PublicKey], AggregatedSignature]] | None = ...,
    ) -> tuple[list[PublicKey], AggregatedSignature]: ...

@final
class Verifier:
    def __init__(self) -> None: ...
    def verify(
        self,
        pub_keys: list[PublicKey],
        message: bytes,
        agg: AggregatedSignature,
        slot: int,
    ) -> None: ...

def keygen(seed: bytes, slot_start: int, slot_end: int) -> tuple[SecretKey, PublicKey]: ...
def sign(
    sk: SecretKey,
    message: bytes,
    slot: int,
    *,
    rng_seed: bytes | None = ...,
) -> Signature: ...
def verify(pk: PublicKey, message: bytes, sig: Signature, slot: int) -> None: ...

class LeanMultisigError(Exception): ...
class KeygenError(LeanMultisigError): ...
class SignError(LeanMultisigError): ...
class VerifyError(LeanMultisigError): ...
class AggregationError(LeanMultisigError): ...
class SerializationError(LeanMultisigError): ...
